config/routes.rb
Rails.application.routes.draw do

      resources :creatures

end

app/models/creature.rb
class Creature < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController

	def index
			@creatures = Creature.all
	end

	def show
		@creature = Creature.find(params[:id])
	end

	def new #display form for new record 

		@creature = Creature.new
		
	end

	def create #saves the new record 
		@creature = Creature.new(allowed_params)

		if @creature.save
			redirect_to @creature
		else 
			render 'new'
		end
	end

	def edit #display form for existing record
		@creature = Creature.find(params[:id])
		
	end

	def update #save changes 
		@creature = Creature.find(params[:id])

		if @creature.update_attributes(allowed_params)
			redirect_to @creature
		else 
			render 'new'
		end

	end

	def destroy #deletes the record
		@creature = Creature.find(params[:id])
		@creature.destroy
		redirect_to creatures_path
	end

	private

		def allowed_params
			params.require(:creature).permit(:name, :description)
			
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/views/creatures/edit.html.erb
<%= bootstrap_form_for @creature do |f| %> <br />

<%= f.label :name %> <br />
<%= f.text_area :name %> <br />

<%= f.label :description %> <br />
<%= f.text_field :description %> <br />

<%= f.submit %>
<% end %>

app/views/creatures/index.html.erb
<%= link_to 'Add Creature', new_creature_path %>

<% @creatures.each do |creature| %>

	<p>
		Name: <%= creature.name %> <br />
		Description: <%= creature.description %> | <%= link_to 'Edit', 
		edit_creature_path(creature) %> | <%= link_to 'Delete', 
		creature, method: :delete %>
	</p>

<% end %>

app/views/creatures/new.html.erb
<%= bootstrap_form_for @creature do |f| %> <br />

<%= f.label :name %> <br />
<%= f.text_area :name %> <br />

<%= f.label :description %> <br />
<%= f.text_field :description %> <br />

<%= f.submit %>
<% end %>

app/views/creatures/show.html.erb
	<p>
		Name: <%= @creature.name %> <br />
		Description: <%= @creature.description %> | <%= link_to 'Edit', 
		edit_creature_path(@creature) %> | <%= link_to 'Delete', 
		@creature, method: :delete %>
	</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>